/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/zhangwenbo/Desktop/learn/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-13332ad0",
    path: "/HTTP/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13332ad0").then(next)
    },
  },
  {
    path: "/HTTP/index.html",
    redirect: "/HTTP/"
  },
  {
    name: "v-748c6ed5",
    path: "/HTTP/%E4%BA%86%E8%A7%A3HTTP%E5%8D%8F%E8%AE%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-748c6ed5").then(next)
    },
  },
  {
    path: "/HTTP/了解HTTP协议.html",
    redirect: "/HTTP/%E4%BA%86%E8%A7%A3HTTP%E5%8D%8F%E8%AE%AE.html"
  },
  {
    path: "/HTTP/了解HTTP协议.html",
    redirect: "/HTTP/%E4%BA%86%E8%A7%A3HTTP%E5%8D%8F%E8%AE%AE.html"
  },
  {
    name: "v-522688ba",
    path: "/cms-vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-522688ba").then(next)
    },
  },
  {
    path: "/cms-vue/index.html",
    redirect: "/cms-vue/"
  },
  {
    name: "v-0ac4d720",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ac4d720").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-25790164",
    path: "/HTTP/%E5%AE%89%E5%85%A8%E7%9A%84HTTPS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25790164").then(next)
    },
  },
  {
    path: "/HTTP/安全的HTTPS.html",
    redirect: "/HTTP/%E5%AE%89%E5%85%A8%E7%9A%84HTTPS.html"
  },
  {
    path: "/HTTP/安全的HTTPS.html",
    redirect: "/HTTP/%E5%AE%89%E5%85%A8%E7%9A%84HTTPS.html"
  },
  {
    name: "v-876bbbf2",
    path: "/cms-vue/%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-876bbbf2").then(next)
    },
  },
  {
    path: "/cms-vue/前端框架搭建.html",
    redirect: "/cms-vue/%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html"
  },
  {
    path: "/cms-vue/前端框架搭建.html",
    redirect: "/cms-vue/%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html"
  },
  {
    name: "v-af43fc9a",
    path: "/cms-vue/%E5%90%8E%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af43fc9a").then(next)
    },
  },
  {
    path: "/cms-vue/后端框架搭建.html",
    redirect: "/cms-vue/%E5%90%8E%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html"
  },
  {
    path: "/cms-vue/后端框架搭建.html",
    redirect: "/cms-vue/%E5%90%8E%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html"
  },
  {
    name: "v-a4ac9f9e",
    path: "/cms-vue/%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4ac9f9e").then(next)
    },
  },
  {
    path: "/cms-vue/功能分析.html",
    redirect: "/cms-vue/%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90.html"
  },
  {
    path: "/cms-vue/功能分析.html",
    redirect: "/cms-vue/%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90.html"
  },
  {
    name: "v-4fec5a70",
    path: "/cms-vue/%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fec5a70").then(next)
    },
  },
  {
    path: "/cms-vue/常用命令.html",
    redirect: "/cms-vue/%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    path: "/cms-vue/常用命令.html",
    redirect: "/cms-vue/%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    name: "v-2e9ca63b",
    path: "/cms-vue/vuex-vue-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e9ca63b").then(next)
    },
  },
  {
    name: "v-5adc07af",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E7%BC%96%E8%BE%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5adc07af").then(next)
    },
  },
  {
    path: "/cms-vue/电子书编辑.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E7%BC%96%E8%BE%91.html"
  },
  {
    path: "/cms-vue/电子书编辑.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E7%BC%96%E8%BE%91.html"
  },
  {
    name: "v-714245fc",
    path: "/cms-vue/%E9%87%8D%E5%AE%9A%E5%90%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-714245fc").then(next)
    },
  },
  {
    path: "/cms-vue/重定向.html",
    redirect: "/cms-vue/%E9%87%8D%E5%AE%9A%E5%90%91.html"
  },
  {
    path: "/cms-vue/重定向.html",
    redirect: "/cms-vue/%E9%87%8D%E5%AE%9A%E5%90%91.html"
  },
  {
    name: "v-2d1ca59a",
    path: "/design-patterns/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d1ca59a").then(next)
    },
  },
  {
    path: "/design-patterns/index.html",
    redirect: "/design-patterns/"
  },
  {
    name: "v-5a235ba3",
    path: "/config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a235ba3").then(next)
    },
  },
  {
    name: "v-81b4560c",
    path: "/cms-vue/%E9%9D%A2%E5%8C%85%E5%B1%91%E5%AF%BC%E8%88%AA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81b4560c").then(next)
    },
  },
  {
    path: "/cms-vue/面包屑导航.html",
    redirect: "/cms-vue/%E9%9D%A2%E5%8C%85%E5%B1%91%E5%AF%BC%E8%88%AA.html"
  },
  {
    path: "/cms-vue/面包屑导航.html",
    redirect: "/cms-vue/%E9%9D%A2%E5%8C%85%E5%B1%91%E5%AF%BC%E8%88%AA.html"
  },
  {
    name: "v-32513a82",
    path: "/cms-vue/%E8%B7%AF%E7%94%B1%E5%92%8C%E6%9D%83%E9%99%90%E6%A0%A1%E9%AA%8C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32513a82").then(next)
    },
  },
  {
    path: "/cms-vue/路由和权限校验.html",
    redirect: "/cms-vue/%E8%B7%AF%E7%94%B1%E5%92%8C%E6%9D%83%E9%99%90%E6%A0%A1%E9%AA%8C.html"
  },
  {
    path: "/cms-vue/路由和权限校验.html",
    redirect: "/cms-vue/%E8%B7%AF%E7%94%B1%E5%92%8C%E6%9D%83%E9%99%90%E6%A0%A1%E9%AA%8C.html"
  },
  {
    name: "v-639443e8",
    path: "/cms-vue/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-639443e8").then(next)
    },
  },
  {
    path: "/cms-vue/项目部署.html",
    redirect: "/cms-vue/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2.html"
  },
  {
    path: "/cms-vue/项目部署.html",
    redirect: "/cms-vue/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2.html"
  },
  {
    name: "v-64262f82",
    path: "/design-patterns/UML%20%E7%B1%BB%E5%9B%BE_02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64262f82").then(next)
    },
  },
  {
    path: "/design-patterns/UML 类图_02.html",
    redirect: "/design-patterns/UML%20%E7%B1%BB%E5%9B%BE_02.html"
  },
  {
    path: "/design-patterns/UML 类图_02.html",
    redirect: "/design-patterns/UML%20%E7%B1%BB%E5%9B%BE_02.html"
  },
  {
    name: "v-55e9eeb5",
    path: "/design-patterns/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F_08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55e9eeb5").then(next)
    },
  },
  {
    path: "/design-patterns/代理模式_08.html",
    redirect: "/design-patterns/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F_08.html"
  },
  {
    path: "/design-patterns/代理模式_08.html",
    redirect: "/design-patterns/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F_08.html"
  },
  {
    name: "v-632d9b2f",
    path: "/design-patterns/%E5%85%B6%E4%BB%96%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F_13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-632d9b2f").then(next)
    },
  },
  {
    path: "/design-patterns/其他设计模式_13.html",
    redirect: "/design-patterns/%E5%85%B6%E4%BB%96%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F_13.html"
  },
  {
    path: "/design-patterns/其他设计模式_13.html",
    redirect: "/design-patterns/%E5%85%B6%E4%BB%96%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F_13.html"
  },
  {
    name: "v-46f56340",
    path: "/design-patterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F_05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46f56340").then(next)
    },
  },
  {
    path: "/design-patterns/单例模式_05.html",
    redirect: "/design-patterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F_05.html"
  },
  {
    path: "/design-patterns/单例模式_05.html",
    redirect: "/design-patterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F_05.html"
  },
  {
    name: "v-7351c691",
    path: "/design-patterns/%E5%B7%A5%E5%8E%82%E6%A8%A1%E5%BC%8F_04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7351c691").then(next)
    },
  },
  {
    path: "/design-patterns/工厂模式_04.html",
    redirect: "/design-patterns/%E5%B7%A5%E5%8E%82%E6%A8%A1%E5%BC%8F_04.html"
  },
  {
    path: "/design-patterns/工厂模式_04.html",
    redirect: "/design-patterns/%E5%B7%A5%E5%8E%82%E6%A8%A1%E5%BC%8F_04.html"
  },
  {
    name: "v-5943132f",
    path: "/design-patterns/%E5%A4%96%E8%A7%82%E6%A8%A1%E5%BC%8F_9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5943132f").then(next)
    },
  },
  {
    path: "/design-patterns/外观模式_9.html",
    redirect: "/design-patterns/%E5%A4%96%E8%A7%82%E6%A8%A1%E5%BC%8F_9.html"
  },
  {
    path: "/design-patterns/外观模式_9.html",
    redirect: "/design-patterns/%E5%A4%96%E8%A7%82%E6%A8%A1%E5%BC%8F_9.html"
  },
  {
    name: "v-4ff104ca",
    path: "/design-patterns/%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F_12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ff104ca").then(next)
    },
  },
  {
    path: "/design-patterns/状态模式_12.html",
    redirect: "/design-patterns/%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F_12.html"
  },
  {
    path: "/design-patterns/状态模式_12.html",
    redirect: "/design-patterns/%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F_12.html"
  },
  {
    name: "v-5c3361db",
    path: "/design-patterns/%E8%A3%85%E9%A5%B0%E5%99%A8%E6%A8%A1%E5%BC%8F_07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c3361db").then(next)
    },
  },
  {
    path: "/design-patterns/装饰器模式_07.html",
    redirect: "/design-patterns/%E8%A3%85%E9%A5%B0%E5%99%A8%E6%A8%A1%E5%BC%8F_07.html"
  },
  {
    path: "/design-patterns/装饰器模式_07.html",
    redirect: "/design-patterns/%E8%A3%85%E9%A5%B0%E5%99%A8%E6%A8%A1%E5%BC%8F_07.html"
  },
  {
    name: "v-273ce594",
    path: "/design-patterns/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F_10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-273ce594").then(next)
    },
  },
  {
    path: "/design-patterns/观察者模式_10.html",
    redirect: "/design-patterns/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F_10.html"
  },
  {
    path: "/design-patterns/观察者模式_10.html",
    redirect: "/design-patterns/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F_10.html"
  },
  {
    name: "v-42b0aa6b",
    path: "/design-patterns/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99_03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42b0aa6b").then(next)
    },
  },
  {
    path: "/design-patterns/设计原则_03.html",
    redirect: "/design-patterns/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99_03.html"
  },
  {
    path: "/design-patterns/设计原则_03.html",
    redirect: "/design-patterns/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99_03.html"
  },
  {
    name: "v-d837454e",
    path: "/design-patterns/%E8%B4%AD%E7%89%A9%E8%BD%A6_14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d837454e").then(next)
    },
  },
  {
    path: "/design-patterns/购物车_14.html",
    redirect: "/design-patterns/%E8%B4%AD%E7%89%A9%E8%BD%A6_14.html"
  },
  {
    path: "/design-patterns/购物车_14.html",
    redirect: "/design-patterns/%E8%B4%AD%E7%89%A9%E8%BD%A6_14.html"
  },
  {
    name: "v-394bcf50",
    path: "/interview-advanced/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-394bcf50").then(next)
    },
  },
  {
    path: "/interview-advanced/index.html",
    redirect: "/interview-advanced/"
  },
  {
    name: "v-25a26300",
    path: "/design-patterns/%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F_06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25a26300").then(next)
    },
  },
  {
    path: "/design-patterns/适配器模式_06.html",
    redirect: "/design-patterns/%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F_06.html"
  },
  {
    path: "/design-patterns/适配器模式_06.html",
    redirect: "/design-patterns/%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F_06.html"
  },
  {
    name: "v-7241972d",
    path: "/design-patterns/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1_01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7241972d").then(next)
    },
  },
  {
    path: "/design-patterns/面向对象_01.html",
    redirect: "/design-patterns/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1_01.html"
  },
  {
    path: "/design-patterns/面向对象_01.html",
    redirect: "/design-patterns/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1_01.html"
  },
  {
    name: "v-3df9de48",
    path: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3df9de48").then(next)
    },
  },
  {
    path: "/interview-advanced/模板编译.html",
    redirect: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html"
  },
  {
    path: "/interview-advanced/模板编译.html",
    redirect: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html"
  },
  {
    name: "v-742c0b9f",
    path: "/design-patterns/%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F_11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-742c0b9f").then(next)
    },
  },
  {
    path: "/design-patterns/迭代器模式_11.html",
    redirect: "/design-patterns/%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F_11.html"
  },
  {
    path: "/design-patterns/迭代器模式_11.html",
    redirect: "/design-patterns/%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F_11.html"
  },
  {
    name: "v-8dc10c0a",
    path: "/interview-advanced/mind-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8dc10c0a").then(next)
    },
  },
  {
    name: "v-1a1aa737",
    path: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a1aa737").then(next)
    },
  },
  {
    path: "/interview-advanced/Vue使用.html",
    redirect: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/interview-advanced/Vue使用.html",
    redirect: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-48eab3f8",
    path: "/interview-advanced/Vue%E7%BB%84%E4%BB%B6%E5%8C%96%E5%92%8C%E5%93%8D%E5%BA%94%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48eab3f8").then(next)
    },
  },
  {
    path: "/interview-advanced/Vue组件化和响应式.html",
    redirect: "/interview-advanced/Vue%E7%BB%84%E4%BB%B6%E5%8C%96%E5%92%8C%E5%93%8D%E5%BA%94%E5%BC%8F.html"
  },
  {
    path: "/interview-advanced/Vue组件化和响应式.html",
    redirect: "/interview-advanced/Vue%E7%BB%84%E4%BB%B6%E5%8C%96%E5%92%8C%E5%93%8D%E5%BA%94%E5%BC%8F.html"
  },
  {
    name: "v-741947da",
    path: "/interview-basis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-741947da").then(next)
    },
  },
  {
    path: "/interview-basis/index.html",
    redirect: "/interview-basis/"
  },
  {
    name: "v-0c6dedf6",
    path: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c6dedf6").then(next)
    },
  },
  {
    path: "/interview-advanced/渲染流程.html",
    redirect: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html"
  },
  {
    path: "/interview-advanced/渲染流程.html",
    redirect: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html"
  },
  {
    name: "v-d9e1fff2",
    path: "/interview-basis/mind-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d9e1fff2").then(next)
    },
  },
  {
    name: "v-64d8620a",
    path: "/koa2/database-design.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64d8620a").then(next)
    },
  },
  {
    name: "v-080f25fb",
    path: "/koa2/error-handling-mechanism.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-080f25fb").then(next)
    },
  },
  {
    name: "v-38c86b6d",
    path: "/koa2/jwt-koa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38c86b6d").then(next)
    },
  },
  {
    name: "v-e3b5594a",
    path: "/koa2/koa-upload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e3b5594a").then(next)
    },
  },
  {
    name: "v-0586fa3b",
    path: "/koa2/koa1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0586fa3b").then(next)
    },
  },
  {
    name: "v-563396ca",
    path: "/koa2/koa2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-563396ca").then(next)
    },
  },
  {
    name: "v-b775220a",
    path: "/koa2/koa3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b775220a").then(next)
    },
  },
  {
    name: "v-04f76312",
    path: "/koa2/nosql-mongodb.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04f76312").then(next)
    },
  },
  {
    name: "v-30f91689",
    path: "/koa2/restful.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30f91689").then(next)
    },
  },
  {
    name: "v-1b815a80",
    path: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b815a80").then(next)
    },
  },
  {
    path: "/node/Node.js在前后端的区别.html",
    redirect: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    path: "/node/Node.js在前后端的区别.html",
    redirect: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    name: "v-84156036",
    path: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84156036").then(next)
    },
  },
  {
    path: "/node/多进程问题如何处理.html",
    redirect: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html"
  },
  {
    path: "/node/多进程问题如何处理.html",
    redirect: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html"
  },
  {
    name: "v-d58a29f4",
    path: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d58a29f4").then(next)
    },
  },
  {
    path: "/HTTP/Web安全威胁浅析.html",
    redirect: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html"
  },
  {
    path: "/HTTP/Web安全威胁浅析.html",
    redirect: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html"
  },
  {
    name: "v-5e30c7e3",
    path: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e30c7e3").then(next)
    },
  },
  {
    path: "/HTTP/HTTP协议结构和通讯原理.html",
    redirect: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/HTTP/HTTP协议结构和通讯原理.html",
    redirect: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-b01acab0",
    path: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b01acab0").then(next)
    },
  },
  {
    path: "/cms-vue/侧边栏.html",
    redirect: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html"
  },
  {
    path: "/cms-vue/侧边栏.html",
    redirect: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html"
  },
  {
    name: "v-6798fa9a",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6798fa9a").then(next)
    },
  },
  {
    path: "/cms-vue/电子书列表.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html"
  },
  {
    path: "/cms-vue/电子书列表.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html"
  },
  {
    name: "v-eed00f1c",
    path: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eed00f1c").then(next)
    },
  },
  {
    path: "/cms-vue/登录页.html",
    redirect: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html"
  },
  {
    path: "/cms-vue/登录页.html",
    redirect: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html"
  },
  {
    name: "v-29ab97db",
    path: "/koa2/restful-practice.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29ab97db").then(next)
    },
  },
  {
    name: "v-524dacba",
    path: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-524dacba").then(next)
    },
  },
  {
    path: "/interview-advanced/虚拟DOM和diff算法.html",
    redirect: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html"
  },
  {
    path: "/interview-advanced/虚拟DOM和diff算法.html",
    redirect: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html"
  },
  {
    name: "v-aa6bf04a",
    path: "/koa2/schema.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa6bf04a").then(next)
    },
  },
  {
    name: "v-1521d2d0",
    path: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1521d2d0").then(next)
    },
  },
  {
    path: "/node/如何快速构建 RESTful 服务.html",
    redirect: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html"
  },
  {
    path: "/node/如何快速构建 RESTful 服务.html",
    redirect: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html"
  },
  {
    name: "v-1193cdf4",
    path: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1193cdf4").then(next)
    },
  },
  {
    path: "/node/Node.js高性能如何做到的.html",
    redirect: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html"
  },
  {
    path: "/node/Node.js高性能如何做到的.html",
    redirect: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html"
  },
  {
    name: "v-7ffcecb0",
    path: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ffcecb0").then(next)
    },
  },
  {
    path: "/HTTP/基于HTTP追加协议.html",
    redirect: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html"
  },
  {
    path: "/HTTP/基于HTTP追加协议.html",
    redirect: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html"
  },
  {
    name: "v-95419a9a",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95419a9a").then(next)
    },
  },
  {
    path: "/cms-vue/电子书新增.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html"
  },
  {
    path: "/cms-vue/电子书新增.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html"
  },
  {
    name: "v-3a223289",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a223289").then(next)
    },
  },
  {
    path: "/cms-vue/电子书上传.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html"
  },
  {
    path: "/cms-vue/电子书上传.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html"
  },
  {
    name: "v-060bca28",
    path: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-060bca28").then(next)
    },
  },
  {
    path: "/HTTP/HTTP的特性和使用.html",
    redirect: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/HTTP/HTTP的特性和使用.html",
    redirect: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-4271bf9b",
    path: "/cms-vue/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4271bf9b").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]