/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/zhangwenbo/Desktop/learn/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1a1aa737",
    path: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a1aa737").then(next)
    },
  },
  {
    path: "/interview-advanced/Vue使用.html",
    redirect: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/interview-advanced/Vue使用.html",
    redirect: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-45fedbc2",
    path: "/interview-advanced/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45fedbc2").then(next)
    },
  },
  {
    path: "/interview-advanced/前端路由原理.html",
    redirect: "/interview-advanced/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/interview-advanced/前端路由原理.html",
    redirect: "/interview-advanced/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-741947da",
    path: "/interview-basis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-741947da").then(next)
    },
  },
  {
    path: "/interview-basis/index.html",
    redirect: "/interview-basis/"
  },
  {
    name: "v-3df9de48",
    path: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3df9de48").then(next)
    },
  },
  {
    path: "/interview-advanced/模板编译.html",
    redirect: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html"
  },
  {
    path: "/interview-advanced/模板编译.html",
    redirect: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html"
  },
  {
    name: "v-0c6dedf6",
    path: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c6dedf6").then(next)
    },
  },
  {
    path: "/interview-advanced/渲染流程.html",
    redirect: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html"
  },
  {
    path: "/interview-advanced/渲染流程.html",
    redirect: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html"
  },
  {
    name: "v-d9e1fff2",
    path: "/interview-basis/mind-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d9e1fff2").then(next)
    },
  },
  {
    name: "v-64d8620a",
    path: "/koa2/database-design.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64d8620a").then(next)
    },
  },
  {
    name: "v-e3b5594a",
    path: "/koa2/koa-upload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e3b5594a").then(next)
    },
  },
  {
    name: "v-080f25fb",
    path: "/koa2/error-handling-mechanism.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-080f25fb").then(next)
    },
  },
  {
    name: "v-38c86b6d",
    path: "/koa2/jwt-koa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38c86b6d").then(next)
    },
  },
  {
    name: "v-0586fa3b",
    path: "/koa2/koa1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0586fa3b").then(next)
    },
  },
  {
    name: "v-b775220a",
    path: "/koa2/koa3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b775220a").then(next)
    },
  },
  {
    name: "v-563396ca",
    path: "/koa2/koa2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-563396ca").then(next)
    },
  },
  {
    name: "v-04f76312",
    path: "/koa2/nosql-mongodb.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04f76312").then(next)
    },
  },
  {
    name: "v-30f91689",
    path: "/koa2/restful.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30f91689").then(next)
    },
  },
  {
    name: "v-1b815a80",
    path: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b815a80").then(next)
    },
  },
  {
    path: "/node/Node.js在前后端的区别.html",
    redirect: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    path: "/node/Node.js在前后端的区别.html",
    redirect: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    name: "v-5e30c7e3",
    path: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e30c7e3").then(next)
    },
  },
  {
    path: "/HTTP/HTTP协议结构和通讯原理.html",
    redirect: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/HTTP/HTTP协议结构和通讯原理.html",
    redirect: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-84156036",
    path: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84156036").then(next)
    },
  },
  {
    path: "/node/多进程问题如何处理.html",
    redirect: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html"
  },
  {
    path: "/node/多进程问题如何处理.html",
    redirect: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html"
  },
  {
    name: "v-d58a29f4",
    path: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d58a29f4").then(next)
    },
  },
  {
    path: "/HTTP/Web安全威胁浅析.html",
    redirect: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html"
  },
  {
    path: "/HTTP/Web安全威胁浅析.html",
    redirect: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html"
  },
  {
    name: "v-6798fa9a",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6798fa9a").then(next)
    },
  },
  {
    path: "/cms-vue/电子书列表.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html"
  },
  {
    path: "/cms-vue/电子书列表.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html"
  },
  {
    name: "v-b01acab0",
    path: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b01acab0").then(next)
    },
  },
  {
    path: "/cms-vue/侧边栏.html",
    redirect: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html"
  },
  {
    path: "/cms-vue/侧边栏.html",
    redirect: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html"
  },
  {
    name: "v-eed00f1c",
    path: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eed00f1c").then(next)
    },
  },
  {
    path: "/cms-vue/登录页.html",
    redirect: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html"
  },
  {
    path: "/cms-vue/登录页.html",
    redirect: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html"
  },
  {
    name: "v-524dacba",
    path: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-524dacba").then(next)
    },
  },
  {
    path: "/interview-advanced/虚拟DOM和diff算法.html",
    redirect: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html"
  },
  {
    path: "/interview-advanced/虚拟DOM和diff算法.html",
    redirect: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html"
  },
  {
    name: "v-aa6bf04a",
    path: "/koa2/schema.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa6bf04a").then(next)
    },
  },
  {
    name: "v-29ab97db",
    path: "/koa2/restful-practice.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29ab97db").then(next)
    },
  },
  {
    name: "v-1521d2d0",
    path: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1521d2d0").then(next)
    },
  },
  {
    path: "/node/如何快速构建 RESTful 服务.html",
    redirect: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html"
  },
  {
    path: "/node/如何快速构建 RESTful 服务.html",
    redirect: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html"
  },
  {
    name: "v-1193cdf4",
    path: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1193cdf4").then(next)
    },
  },
  {
    path: "/node/Node.js高性能如何做到的.html",
    redirect: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html"
  },
  {
    path: "/node/Node.js高性能如何做到的.html",
    redirect: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html"
  },
  {
    name: "v-7ffcecb0",
    path: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ffcecb0").then(next)
    },
  },
  {
    path: "/HTTP/基于HTTP追加协议.html",
    redirect: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html"
  },
  {
    path: "/HTTP/基于HTTP追加协议.html",
    redirect: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html"
  },
  {
    name: "v-95419a9a",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95419a9a").then(next)
    },
  },
  {
    path: "/cms-vue/电子书新增.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html"
  },
  {
    path: "/cms-vue/电子书新增.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html"
  },
  {
    name: "v-3a223289",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a223289").then(next)
    },
  },
  {
    path: "/cms-vue/电子书上传.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html"
  },
  {
    path: "/cms-vue/电子书上传.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html"
  },
  {
    name: "v-3243178f",
    path: "/interview-advanced/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3243178f").then(next)
    },
  },
  {
    name: "v-060bca28",
    path: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-060bca28").then(next)
    },
  },
  {
    path: "/HTTP/HTTP的特性和使用.html",
    redirect: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/HTTP/HTTP的特性和使用.html",
    redirect: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-4271bf9b",
    path: "/cms-vue/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4271bf9b").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]