/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\我的\\study-notes\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-098147e2",
    path: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-098147e2").then(next)
    },
  },
  {
    path: "/HTTP/HTTP协议结构和通讯原理.html",
    redirect: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/HTTP/HTTP协议结构和通讯原理.html",
    redirect: "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-0cf7f7d0",
    path: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cf7f7d0").then(next)
    },
  },
  {
    path: "/HTTP/HTTP的特性和使用.html",
    redirect: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/HTTP/HTTP的特性和使用.html",
    redirect: "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-2975a19c",
    path: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2975a19c").then(next)
    },
  },
  {
    path: "/HTTP/Web安全威胁浅析.html",
    redirect: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html"
  },
  {
    path: "/HTTP/Web安全威胁浅析.html",
    redirect: "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html"
  },
  {
    name: "v-81535db8",
    path: "/HTTP/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81535db8").then(next)
    },
  },
  {
    path: "/HTTP/index.html",
    redirect: "/HTTP/"
  },
  {
    name: "v-748da601",
    path: "/HTTP/%E4%BA%86%E8%A7%A3HTTP%E5%8D%8F%E8%AE%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-748da601").then(next)
    },
  },
  {
    path: "/HTTP/了解HTTP协议.html",
    redirect: "/HTTP/%E4%BA%86%E8%A7%A3HTTP%E5%8D%8F%E8%AE%AE.html"
  },
  {
    path: "/HTTP/了解HTTP协议.html",
    redirect: "/HTTP/%E4%BA%86%E8%A7%A3HTTP%E5%8D%8F%E8%AE%AE.html"
  },
  {
    name: "v-20ebb6e0",
    path: "/HTTP/%E5%AE%89%E5%85%A8%E7%9A%84HTTPS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20ebb6e0").then(next)
    },
  },
  {
    path: "/HTTP/安全的HTTPS.html",
    redirect: "/HTTP/%E5%AE%89%E5%85%A8%E7%9A%84HTTPS.html"
  },
  {
    path: "/HTTP/安全的HTTPS.html",
    redirect: "/HTTP/%E5%AE%89%E5%85%A8%E7%9A%84HTTPS.html"
  },
  {
    name: "v-4653fafe",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4653fafe").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7c86d5dc",
    path: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c86d5dc").then(next)
    },
  },
  {
    path: "/HTTP/基于HTTP追加协议.html",
    redirect: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html"
  },
  {
    path: "/HTTP/基于HTTP追加协议.html",
    redirect: "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html"
  },
  {
    name: "v-21d20108",
    path: "/cms-vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21d20108").then(next)
    },
  },
  {
    path: "/cms-vue/index.html",
    redirect: "/cms-vue/"
  },
  {
    name: "v-f03f0ea6",
    path: "/cms-vue/vuex-vue-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f03f0ea6").then(next)
    },
  },
  {
    name: "v-48bcb60d",
    path: "/cms-vue/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48bcb60d").then(next)
    },
  },
  {
    name: "v-01366d1a",
    path: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01366d1a").then(next)
    },
  },
  {
    path: "/cms-vue/侧边栏.html",
    redirect: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html"
  },
  {
    path: "/cms-vue/侧边栏.html",
    redirect: "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html"
  },
  {
    name: "v-023ba0f9",
    path: "/cms-vue/%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-023ba0f9").then(next)
    },
  },
  {
    path: "/cms-vue/前端框架搭建.html",
    redirect: "/cms-vue/%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html"
  },
  {
    path: "/cms-vue/前端框架搭建.html",
    redirect: "/cms-vue/%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html"
  },
  {
    name: "v-77a69c23",
    path: "/cms-vue/%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77a69c23").then(next)
    },
  },
  {
    path: "/cms-vue/功能分析.html",
    redirect: "/cms-vue/%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90.html"
  },
  {
    path: "/cms-vue/功能分析.html",
    redirect: "/cms-vue/%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90.html"
  },
  {
    name: "v-2360feb6",
    path: "/cms-vue/%E5%90%8E%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2360feb6").then(next)
    },
  },
  {
    path: "/cms-vue/后端框架搭建.html",
    redirect: "/cms-vue/%E5%90%8E%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html"
  },
  {
    path: "/cms-vue/后端框架搭建.html",
    redirect: "/cms-vue/%E5%90%8E%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html"
  },
  {
    name: "v-19e94662",
    path: "/cms-vue/%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19e94662").then(next)
    },
  },
  {
    path: "/cms-vue/常用命令.html",
    redirect: "/cms-vue/%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    path: "/cms-vue/常用命令.html",
    redirect: "/cms-vue/%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    name: "v-696657fb",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-696657fb").then(next)
    },
  },
  {
    path: "/cms-vue/电子书上传.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html"
  },
  {
    path: "/cms-vue/电子书上传.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html"
  },
  {
    name: "v-0910afb6",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0910afb6").then(next)
    },
  },
  {
    path: "/cms-vue/电子书列表.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html"
  },
  {
    path: "/cms-vue/电子书列表.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html"
  },
  {
    name: "v-36b94fb6",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36b94fb6").then(next)
    },
  },
  {
    path: "/cms-vue/电子书新增.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html"
  },
  {
    path: "/cms-vue/电子书新增.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html"
  },
  {
    name: "v-ebbfa5be",
    path: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E7%BC%96%E8%BE%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ebbfa5be").then(next)
    },
  },
  {
    path: "/cms-vue/电子书编辑.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E7%BC%96%E8%BE%91.html"
  },
  {
    path: "/cms-vue/电子书编辑.html",
    redirect: "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E7%BC%96%E8%BE%91.html"
  },
  {
    name: "v-3c486a38",
    path: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c486a38").then(next)
    },
  },
  {
    path: "/cms-vue/登录页.html",
    redirect: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html"
  },
  {
    path: "/cms-vue/登录页.html",
    redirect: "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html"
  },
  {
    name: "v-61a39a18",
    path: "/cms-vue/%E8%B7%AF%E7%94%B1%E5%92%8C%E6%9D%83%E9%99%90%E6%A0%A1%E9%AA%8C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61a39a18").then(next)
    },
  },
  {
    path: "/cms-vue/路由和权限校验.html",
    redirect: "/cms-vue/%E8%B7%AF%E7%94%B1%E5%92%8C%E6%9D%83%E9%99%90%E6%A0%A1%E9%AA%8C.html"
  },
  {
    path: "/cms-vue/路由和权限校验.html",
    redirect: "/cms-vue/%E8%B7%AF%E7%94%B1%E5%92%8C%E6%9D%83%E9%99%90%E6%A0%A1%E9%AA%8C.html"
  },
  {
    name: "v-6af3cf24",
    path: "/cms-vue/%E9%87%8D%E5%AE%9A%E5%90%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6af3cf24").then(next)
    },
  },
  {
    path: "/cms-vue/重定向.html",
    redirect: "/cms-vue/%E9%87%8D%E5%AE%9A%E5%90%91.html"
  },
  {
    path: "/cms-vue/重定向.html",
    redirect: "/cms-vue/%E9%87%8D%E5%AE%9A%E5%90%91.html"
  },
  {
    name: "v-232c0b28",
    path: "/cms-vue/%E9%9D%A2%E5%8C%85%E5%B1%91%E5%AF%BC%E8%88%AA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-232c0b28").then(next)
    },
  },
  {
    path: "/cms-vue/面包屑导航.html",
    redirect: "/cms-vue/%E9%9D%A2%E5%8C%85%E5%B1%91%E5%AF%BC%E8%88%AA.html"
  },
  {
    path: "/cms-vue/面包屑导航.html",
    redirect: "/cms-vue/%E9%9D%A2%E5%8C%85%E5%B1%91%E5%AF%BC%E8%88%AA.html"
  },
  {
    name: "v-cf9a6c04",
    path: "/cms-vue/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf9a6c04").then(next)
    },
  },
  {
    path: "/cms-vue/项目部署.html",
    redirect: "/cms-vue/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2.html"
  },
  {
    path: "/cms-vue/项目部署.html",
    redirect: "/cms-vue/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2.html"
  },
  {
    name: "v-0488f9a2",
    path: "/config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0488f9a2").then(next)
    },
  },
  {
    name: "v-0d35aeb8",
    path: "/data-structure/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d35aeb8").then(next)
    },
  },
  {
    path: "/data-structure/index.html",
    redirect: "/data-structure/"
  },
  {
    name: "v-79bffee8",
    path: "/design-patterns/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79bffee8").then(next)
    },
  },
  {
    path: "/design-patterns/index.html",
    redirect: "/design-patterns/"
  },
  {
    name: "v-72491c4a",
    path: "/data-structure/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72491c4a").then(next)
    },
  },
  {
    path: "/data-structure/数据结构.html",
    redirect: "/data-structure/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    path: "/data-structure/数据结构.html",
    redirect: "/data-structure/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    name: "v-3b013918",
    path: "/design-patterns/UML%20%E7%B1%BB%E5%9B%BE_02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b013918").then(next)
    },
  },
  {
    path: "/design-patterns/UML 类图_02.html",
    redirect: "/design-patterns/UML%20%E7%B1%BB%E5%9B%BE_02.html"
  },
  {
    path: "/design-patterns/UML 类图_02.html",
    redirect: "/design-patterns/UML%20%E7%B1%BB%E5%9B%BE_02.html"
  },
  {
    name: "v-6e5f47b2",
    path: "/design-patterns/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F_08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e5f47b2").then(next)
    },
  },
  {
    path: "/design-patterns/代理模式_08.html",
    redirect: "/design-patterns/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F_08.html"
  },
  {
    path: "/design-patterns/代理模式_08.html",
    redirect: "/design-patterns/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F_08.html"
  },
  {
    name: "v-23b8dba1",
    path: "/design-patterns/%E5%85%B6%E4%BB%96%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F_13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23b8dba1").then(next)
    },
  },
  {
    path: "/design-patterns/其他设计模式_13.html",
    redirect: "/design-patterns/%E5%85%B6%E4%BB%96%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F_13.html"
  },
  {
    path: "/design-patterns/其他设计模式_13.html",
    redirect: "/design-patterns/%E5%85%B6%E4%BB%96%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F_13.html"
  },
  {
    name: "v-4f6bbbd2",
    path: "/design-patterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F_05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f6bbbd2").then(next)
    },
  },
  {
    path: "/design-patterns/单例模式_05.html",
    redirect: "/design-patterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F_05.html"
  },
  {
    path: "/design-patterns/单例模式_05.html",
    redirect: "/design-patterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F_05.html"
  },
  {
    name: "v-396a3521",
    path: "/design-patterns/%E5%A4%96%E8%A7%82%E6%A8%A1%E5%BC%8F_9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-396a3521").then(next)
    },
  },
  {
    path: "/design-patterns/外观模式_9.html",
    redirect: "/design-patterns/%E5%A4%96%E8%A7%82%E6%A8%A1%E5%BC%8F_9.html"
  },
  {
    path: "/design-patterns/外观模式_9.html",
    redirect: "/design-patterns/%E5%A4%96%E8%A7%82%E6%A8%A1%E5%BC%8F_9.html"
  },
  {
    name: "v-338f97fa",
    path: "/design-patterns/%E5%B7%A5%E5%8E%82%E6%A8%A1%E5%BC%8F_04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-338f97fa").then(next)
    },
  },
  {
    path: "/design-patterns/工厂模式_04.html",
    redirect: "/design-patterns/%E5%B7%A5%E5%8E%82%E6%A8%A1%E5%BC%8F_04.html"
  },
  {
    path: "/design-patterns/工厂模式_04.html",
    redirect: "/design-patterns/%E5%B7%A5%E5%8E%82%E6%A8%A1%E5%BC%8F_04.html"
  },
  {
    name: "v-7a511b88",
    path: "/design-patterns/%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F_12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a511b88").then(next)
    },
  },
  {
    path: "/design-patterns/状态模式_12.html",
    redirect: "/design-patterns/%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F_12.html"
  },
  {
    path: "/design-patterns/状态模式_12.html",
    redirect: "/design-patterns/%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F_12.html"
  },
  {
    name: "v-d4e5ae66",
    path: "/design-patterns/%E8%A3%85%E9%A5%B0%E5%99%A8%E6%A8%A1%E5%BC%8F_07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d4e5ae66").then(next)
    },
  },
  {
    path: "/design-patterns/装饰器模式_07.html",
    redirect: "/design-patterns/%E8%A3%85%E9%A5%B0%E5%99%A8%E6%A8%A1%E5%BC%8F_07.html"
  },
  {
    path: "/design-patterns/装饰器模式_07.html",
    redirect: "/design-patterns/%E8%A3%85%E9%A5%B0%E5%99%A8%E6%A8%A1%E5%BC%8F_07.html"
  },
  {
    name: "v-25bb5428",
    path: "/design-patterns/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F_10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25bb5428").then(next)
    },
  },
  {
    path: "/design-patterns/观察者模式_10.html",
    redirect: "/design-patterns/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F_10.html"
  },
  {
    path: "/design-patterns/观察者模式_10.html",
    redirect: "/design-patterns/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F_10.html"
  },
  {
    name: "v-94d1d046",
    path: "/design-patterns/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99_03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-94d1d046").then(next)
    },
  },
  {
    path: "/design-patterns/设计原则_03.html",
    redirect: "/design-patterns/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99_03.html"
  },
  {
    path: "/design-patterns/设计原则_03.html",
    redirect: "/design-patterns/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99_03.html"
  },
  {
    name: "v-123d914b",
    path: "/design-patterns/%E8%B4%AD%E7%89%A9%E8%BD%A6_14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-123d914b").then(next)
    },
  },
  {
    path: "/design-patterns/购物车_14.html",
    redirect: "/design-patterns/%E8%B4%AD%E7%89%A9%E8%BD%A6_14.html"
  },
  {
    path: "/design-patterns/购物车_14.html",
    redirect: "/design-patterns/%E8%B4%AD%E7%89%A9%E8%BD%A6_14.html"
  },
  {
    name: "v-a4f45ade",
    path: "/design-patterns/%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F_11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4f45ade").then(next)
    },
  },
  {
    path: "/design-patterns/迭代器模式_11.html",
    redirect: "/design-patterns/%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F_11.html"
  },
  {
    path: "/design-patterns/迭代器模式_11.html",
    redirect: "/design-patterns/%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F_11.html"
  },
  {
    name: "v-5efc29f2",
    path: "/design-patterns/%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F_06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5efc29f2").then(next)
    },
  },
  {
    path: "/design-patterns/适配器模式_06.html",
    redirect: "/design-patterns/%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F_06.html"
  },
  {
    path: "/design-patterns/适配器模式_06.html",
    redirect: "/design-patterns/%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F_06.html"
  },
  {
    name: "v-35aff6c2",
    path: "/design-patterns/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1_01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35aff6c2").then(next)
    },
  },
  {
    path: "/design-patterns/面向对象_01.html",
    redirect: "/design-patterns/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1_01.html"
  },
  {
    path: "/design-patterns/面向对象_01.html",
    redirect: "/design-patterns/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1_01.html"
  },
  {
    name: "v-87b4dfba",
    path: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87b4dfba").then(next)
    },
  },
  {
    path: "/interview-advanced/Vue使用.html",
    redirect: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/interview-advanced/Vue使用.html",
    redirect: "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-67dc94e4",
    path: "/interview-advanced/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67dc94e4").then(next)
    },
  },
  {
    path: "/interview-advanced/index.html",
    redirect: "/interview-advanced/"
  },
  {
    name: "v-28a9ec38",
    path: "/interview-advanced/Vue%E7%BB%84%E4%BB%B6%E5%8C%96%E5%92%8C%E5%93%8D%E5%BA%94%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28a9ec38").then(next)
    },
  },
  {
    path: "/interview-advanced/Vue组件化和响应式.html",
    redirect: "/interview-advanced/Vue%E7%BB%84%E4%BB%B6%E5%8C%96%E5%92%8C%E5%93%8D%E5%BA%94%E5%BC%8F.html"
  },
  {
    path: "/interview-advanced/Vue组件化和响应式.html",
    redirect: "/interview-advanced/Vue%E7%BB%84%E4%BB%B6%E5%8C%96%E5%92%8C%E5%93%8D%E5%BA%94%E5%BC%8F.html"
  },
  {
    name: "v-0c67ade7",
    path: "/interview-advanced/mind-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c67ade7").then(next)
    },
  },
  {
    name: "v-8bbb7fea",
    path: "/interview-advanced/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8bbb7fea").then(next)
    },
  },
  {
    path: "/interview-advanced/前端路由原理.html",
    redirect: "/interview-advanced/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/interview-advanced/前端路由原理.html",
    redirect: "/interview-advanced/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-6e13027b",
    path: "/interview-advanced/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e13027b").then(next)
    },
  },
  {
    name: "v-4fc42670",
    path: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fc42670").then(next)
    },
  },
  {
    path: "/interview-advanced/模板编译.html",
    redirect: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html"
  },
  {
    path: "/interview-advanced/模板编译.html",
    redirect: "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html"
  },
  {
    name: "v-49ce84a6",
    path: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49ce84a6").then(next)
    },
  },
  {
    path: "/interview-advanced/虚拟DOM和diff算法.html",
    redirect: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html"
  },
  {
    path: "/interview-advanced/虚拟DOM和diff算法.html",
    redirect: "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html"
  },
  {
    name: "v-1e38361e",
    path: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e38361e").then(next)
    },
  },
  {
    path: "/interview-advanced/渲染流程.html",
    redirect: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html"
  },
  {
    path: "/interview-advanced/渲染流程.html",
    redirect: "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html"
  },
  {
    name: "v-12310ef9",
    path: "/interview-basis/mind-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12310ef9").then(next)
    },
  },
  {
    name: "v-7e86bdb0",
    path: "/interview-basis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e86bdb0").then(next)
    },
  },
  {
    path: "/interview-basis/index.html",
    redirect: "/interview-basis/"
  },
  {
    name: "v-1b1a8db2",
    path: "/koa2/database-design.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b1a8db2").then(next)
    },
  },
  {
    name: "v-08105d27",
    path: "/koa2/error-handling-mechanism.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08105d27").then(next)
    },
  },
  {
    name: "v-b38da4ce",
    path: "/koa2/jwt-koa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b38da4ce").then(next)
    },
  },
  {
    name: "v-8fe276f2",
    path: "/koa2/koa-upload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8fe276f2").then(next)
    },
  },
  {
    name: "v-7e8fcd67",
    path: "/koa2/koa1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e8fcd67").then(next)
    },
  },
  {
    name: "v-4def07c7",
    path: "/koa2/koa2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4def07c7").then(next)
    },
  },
  {
    name: "v-1d4e4227",
    path: "/koa2/koa3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d4e4227").then(next)
    },
  },
  {
    name: "v-0c672ea3",
    path: "/koa2/nosql-mongodb.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c672ea3").then(next)
    },
  },
  {
    name: "v-db0eb1f2",
    path: "/koa2/restful-practice.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db0eb1f2").then(next)
    },
  },
  {
    name: "v-c32c4e96",
    path: "/koa2/restful.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c32c4e96").then(next)
    },
  },
  {
    name: "v-00c535f2",
    path: "/koa2/schema.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00c535f2").then(next)
    },
  },
  {
    name: "v-b1e94fc0",
    path: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1e94fc0").then(next)
    },
  },
  {
    path: "/node/Node.js高性能如何做到的.html",
    redirect: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html"
  },
  {
    path: "/node/Node.js高性能如何做到的.html",
    redirect: "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html"
  },
  {
    name: "v-5e4b6bac",
    path: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e4b6bac").then(next)
    },
  },
  {
    path: "/node/Node.js在前后端的区别.html",
    redirect: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    path: "/node/Node.js在前后端的区别.html",
    redirect: "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    name: "v-ba7e5fde",
    path: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba7e5fde").then(next)
    },
  },
  {
    path: "/node/多进程问题如何处理.html",
    redirect: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html"
  },
  {
    path: "/node/多进程问题如何处理.html",
    redirect: "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html"
  },
  {
    name: "v-b99b1e08",
    path: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b99b1e08").then(next)
    },
  },
  {
    path: "/node/如何快速构建 RESTful 服务.html",
    redirect: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html"
  },
  {
    path: "/node/如何快速构建 RESTful 服务.html",
    redirect: "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]