/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Notes",
  "description": "自我学习",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/HTTP/",
      "relativePath": "HTTP/README.md",
      "key": "v-13332ad0",
      "path": "/HTTP/",
      "lastUpdated": "5/26/2021, 5:56:39 PM"
    },
    {
      "title": "了解HTTP协议",
      "frontmatter": {},
      "regularPath": "/HTTP/%E4%BA%86%E8%A7%A3HTTP%E5%8D%8F%E8%AE%AE.html",
      "relativePath": "HTTP/了解HTTP协议.md",
      "key": "v-748c6ed5",
      "path": "/HTTP/%E4%BA%86%E8%A7%A3HTTP%E5%8D%8F%E8%AE%AE.html",
      "headers": [
        {
          "level": 2,
          "title": "浏览器背后的故事",
          "slug": "浏览器背后的故事"
        },
        {
          "level": 2,
          "title": "HTTP 的生平经历",
          "slug": "http-的生平经历"
        },
        {
          "level": 2,
          "title": "透过 TCP/IP 看 HTTP",
          "slug": "透过-tcp-ip-看-http"
        },
        {
          "level": 3,
          "title": "TCP/IP 协议层",
          "slug": "tcp-ip-协议层"
        },
        {
          "level": 3,
          "title": "数据封装的过程",
          "slug": "数据封装的过程"
        },
        {
          "level": 3,
          "title": "HTTP数据传输过程",
          "slug": "http数据传输过程"
        },
        {
          "level": 3,
          "title": "传输层-TCP三次握手",
          "slug": "传输层-tcp三次握手"
        },
        {
          "level": 2,
          "title": "DNS 域名解析",
          "slug": "dns-域名解析"
        },
        {
          "level": 2,
          "title": "HTTP 事务处理过程",
          "slug": "http-事务处理过程"
        }
      ],
      "lastUpdated": "5/27/2021, 6:26:29 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/cms-vue/",
      "relativePath": "cms-vue/README.md",
      "key": "v-522688ba",
      "path": "/cms-vue/",
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "安全的 HTTPS",
      "frontmatter": {},
      "regularPath": "/HTTP/%E5%AE%89%E5%85%A8%E7%9A%84HTTPS.html",
      "relativePath": "HTTP/安全的HTTPS.md",
      "key": "v-25790164",
      "path": "/HTTP/%E5%AE%89%E5%85%A8%E7%9A%84HTTPS.html",
      "headers": [
        {
          "level": 2,
          "title": "HTTPS协议概述",
          "slug": "https协议概述"
        },
        {
          "level": 2,
          "title": "HTTPS 功能介绍",
          "slug": "https-功能介绍"
        },
        {
          "level": 2,
          "title": "使用成本",
          "slug": "使用成本"
        },
        {
          "level": 2,
          "title": "对性能的影响",
          "slug": "对性能的影响"
        }
      ],
      "lastUpdated": "8/25/2021, 4:44:53 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "开始 →",
        "actionLink": "/koa2/restful",
        "features": null
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0ac4d720",
      "path": "/",
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Vuex 和 Vue-router 进阶",
      "frontmatter": {},
      "regularPath": "/cms-vue/vuex-vue-router.html",
      "relativePath": "cms-vue/vuex-vue-router.md",
      "key": "v-2e9ca63b",
      "path": "/cms-vue/vuex-vue-router.html",
      "headers": [
        {
          "level": 2,
          "title": "Vuex 原理解析",
          "slug": "vuex-原理解析"
        },
        {
          "level": 2,
          "title": "vue-router 实现原理",
          "slug": "vue-router-实现原理"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "前端框架搭建",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html",
      "relativePath": "cms-vue/前端框架搭建.md",
      "key": "v-876bbbf2",
      "path": "/cms-vue/%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html",
      "headers": [
        {
          "level": 2,
          "title": "项目初始化",
          "slug": "项目初始化"
        },
        {
          "level": 2,
          "title": "项目精简",
          "slug": "项目精简"
        },
        {
          "level": 2,
          "title": "项目结构",
          "slug": "项目结构"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "后端框架搭建",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E5%90%8E%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html",
      "relativePath": "cms-vue/后端框架搭建.md",
      "key": "v-af43fc9a",
      "path": "/cms-vue/%E5%90%8E%E7%AB%AF%E6%A1%86%E6%9E%B6%E6%90%AD%E5%BB%BA.html",
      "headers": [
        {
          "level": 2,
          "title": "Koa简介",
          "slug": "koa简介"
        },
        {
          "level": 2,
          "title": "项目初始化",
          "slug": "项目初始化"
        },
        {
          "level": 2,
          "title": "文件结构",
          "slug": "文件结构"
        },
        {
          "level": 2,
          "title": "项目搭建",
          "slug": "项目搭建"
        },
        {
          "level": 2,
          "title": "别名路径配置",
          "slug": "别名路径配置"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "功能分析",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90.html",
      "relativePath": "cms-vue/功能分析.md",
      "key": "v-a4ac9f9e",
      "path": "/cms-vue/%E5%8A%9F%E8%83%BD%E5%88%86%E6%9E%90.html",
      "headers": [
        {
          "level": 2,
          "title": "epub 电子书",
          "slug": "epub-电子书"
        },
        {
          "level": 2,
          "title": "Nginx 搭建",
          "slug": "nginx-搭建"
        },
        {
          "level": 3,
          "title": "安装 nginx",
          "slug": "安装-nginx"
        },
        {
          "level": 3,
          "title": "修改配置文件",
          "slug": "修改配置文件"
        },
        {
          "level": 3,
          "title": "Nginx 启动相关",
          "slug": "nginx-启动相关"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "常用命令",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
      "relativePath": "cms-vue/常用命令.md",
      "key": "v-4fec5a70",
      "path": "/cms-vue/%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
      "headers": [
        {
          "level": 2,
          "title": "PM2 常用命令",
          "slug": "pm2-常用命令"
        },
        {
          "level": 2,
          "title": "防止服务器断开连接",
          "slug": "防止服务器断开连接"
        },
        {
          "level": 2,
          "title": "CentOS 7下启动、关闭、重启、查看MySQL服务",
          "slug": "centos-7下启动、关闭、重启、查看mysql服务"
        },
        {
          "level": 2,
          "title": "Nginx常用命令",
          "slug": "nginx常用命令"
        },
        {
          "level": 2,
          "title": "Nginx 的配置文件和最佳实践",
          "slug": "nginx-的配置文件和最佳实践"
        }
      ],
      "lastUpdated": "5/14/2021, 5:10:17 PM"
    },
    {
      "title": "电子书编辑",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E7%BC%96%E8%BE%91.html",
      "relativePath": "cms-vue/电子书编辑.md",
      "key": "v-5adc07af",
      "path": "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E7%BC%96%E8%BE%91.html",
      "headers": [
        {
          "level": 2,
          "title": "服务端",
          "slug": "服务端"
        },
        {
          "level": 2,
          "title": "客户端",
          "slug": "客户端"
        }
      ],
      "lastUpdated": "5/14/2021, 5:10:17 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-5a235ba3",
      "path": "/config.html",
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/design-patterns/",
      "relativePath": "design-patterns/README.md",
      "key": "v-2d1ca59a",
      "path": "/design-patterns/",
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "重定向",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E9%87%8D%E5%AE%9A%E5%90%91.html",
      "relativePath": "cms-vue/重定向.md",
      "key": "v-714245fc",
      "path": "/cms-vue/%E9%87%8D%E5%AE%9A%E5%90%91.html",
      "headers": [
        {
          "level": 2,
          "title": "登录重定向",
          "slug": "登录重定向"
        },
        {
          "level": 2,
          "title": "重定向组件",
          "slug": "重定向组件"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "路由和权限校验",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E8%B7%AF%E7%94%B1%E5%92%8C%E6%9D%83%E9%99%90%E6%A0%A1%E9%AA%8C.html",
      "relativePath": "cms-vue/路由和权限校验.md",
      "key": "v-32513a82",
      "path": "/cms-vue/%E8%B7%AF%E7%94%B1%E5%92%8C%E6%9D%83%E9%99%90%E6%A0%A1%E9%AA%8C.html",
      "headers": [
        {
          "level": 2,
          "title": "路由处理逻辑分析",
          "slug": "路由处理逻辑分析"
        },
        {
          "level": 3,
          "title": "代码分析",
          "slug": "代码分析"
        },
        {
          "level": 2,
          "title": "动态路由源码分析",
          "slug": "动态路由源码分析"
        },
        {
          "level": 3,
          "title": "相关代码",
          "slug": "相关代码"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "项目部署",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2.html",
      "relativePath": "cms-vue/项目部署.md",
      "key": "v-639443e8",
      "path": "/cms-vue/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2.html",
      "headers": [
        {
          "level": 3,
          "title": "shell命令控制自动",
          "slug": "shell命令控制自动"
        }
      ],
      "lastUpdated": "5/26/2021, 5:56:39 PM"
    },
    {
      "title": "UML类图",
      "frontmatter": {},
      "regularPath": "/design-patterns/UML%20%E7%B1%BB%E5%9B%BE_02.html",
      "relativePath": "design-patterns/UML 类图_02.md",
      "key": "v-64262f82",
      "path": "/design-patterns/UML%20%E7%B1%BB%E5%9B%BE_02.html",
      "headers": [
        {
          "level": 2,
          "title": "类图",
          "slug": "类图"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "代理模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F_08.html",
      "relativePath": "design-patterns/代理模式_08.md",
      "key": "v-55e9eeb5",
      "path": "/design-patterns/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F_08.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、演示",
          "slug": "二、演示"
        },
        {
          "level": 2,
          "title": "三、场景",
          "slug": "三、场景"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "其他设计模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E5%85%B6%E4%BB%96%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F_13.html",
      "relativePath": "design-patterns/其他设计模式_13.md",
      "key": "v-632d9b2f",
      "path": "/design-patterns/%E5%85%B6%E4%BB%96%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F_13.html",
      "headers": [
        {
          "level": 2,
          "title": "原型模式",
          "slug": "原型模式"
        },
        {
          "level": 2,
          "title": "桥接模式",
          "slug": "桥接模式"
        },
        {
          "level": 2,
          "title": "组合模式",
          "slug": "组合模式"
        },
        {
          "level": 2,
          "title": "享元模式",
          "slug": "享元模式"
        },
        {
          "level": 2,
          "title": "策略模式",
          "slug": "策略模式"
        },
        {
          "level": 2,
          "title": "模板方法模式",
          "slug": "模板方法模式"
        },
        {
          "level": 2,
          "title": "和职责链模式",
          "slug": "和职责链模式"
        },
        {
          "level": 2,
          "title": "命令模式",
          "slug": "命令模式"
        },
        {
          "level": 2,
          "title": "备忘录模式",
          "slug": "备忘录模式"
        },
        {
          "level": 2,
          "title": "中介者模式",
          "slug": "中介者模式"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "单例模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F_05.html",
      "relativePath": "design-patterns/单例模式_05.md",
      "key": "v-46f56340",
      "path": "/design-patterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F_05.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、演示",
          "slug": "二、演示"
        },
        {
          "level": 2,
          "title": "三、场景",
          "slug": "三、场景"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        },
        {
          "level": 2,
          "title": "五、示例",
          "slug": "五、示例"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "状态模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F_12.html",
      "relativePath": "design-patterns/状态模式_12.md",
      "key": "v-4ff104ca",
      "path": "/design-patterns/%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F_12.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、演示",
          "slug": "二、演示"
        },
        {
          "level": 2,
          "title": "三、场景",
          "slug": "三、场景"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        },
        {
          "level": 2,
          "title": "五、示例",
          "slug": "五、示例"
        },
        {
          "level": 3,
          "title": "实现一个Promise",
          "slug": "实现一个promise"
        },
        {
          "level": 3,
          "title": "模拟红绿灯",
          "slug": "模拟红绿灯"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "外观模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E5%A4%96%E8%A7%82%E6%A8%A1%E5%BC%8F_9.html",
      "relativePath": "design-patterns/外观模式_9.md",
      "key": "v-5943132f",
      "path": "/design-patterns/%E5%A4%96%E8%A7%82%E6%A8%A1%E5%BC%8F_9.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、场景",
          "slug": "二、场景"
        },
        {
          "level": 2,
          "title": "三、总结",
          "slug": "三、总结"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "面包屑导航",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E9%9D%A2%E5%8C%85%E5%B1%91%E5%AF%BC%E8%88%AA.html",
      "relativePath": "cms-vue/面包屑导航.md",
      "key": "v-81b4560c",
      "path": "/cms-vue/%E9%9D%A2%E5%8C%85%E5%B1%91%E5%AF%BC%E8%88%AA.html",
      "headers": [
        {
          "level": 2,
          "title": "el-breadcrumb-item",
          "slug": "el-breadcrumb-item"
        },
        {
          "level": 2,
          "title": "路由与面包屑导航映射",
          "slug": "路由与面包屑导航映射"
        },
        {
          "level": 3,
          "title": "生成面包屑导航",
          "slug": "生成面包屑导航"
        },
        {
          "level": 3,
          "title": "渲染面包屑导航",
          "slug": "渲染面包屑导航"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "工厂模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E5%B7%A5%E5%8E%82%E6%A8%A1%E5%BC%8F_04.html",
      "relativePath": "design-patterns/工厂模式_04.md",
      "key": "v-7351c691",
      "path": "/design-patterns/%E5%B7%A5%E5%8E%82%E6%A8%A1%E5%BC%8F_04.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、场景",
          "slug": "二、场景"
        },
        {
          "level": 2,
          "title": "三、阅读经典lib源码",
          "slug": "三、阅读经典lib源码"
        },
        {
          "level": 2,
          "title": "四、设计原则验证",
          "slug": "四、设计原则验证"
        },
        {
          "level": 2,
          "title": "五、示例",
          "slug": "五、示例"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "装饰器模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E8%A3%85%E9%A5%B0%E5%99%A8%E6%A8%A1%E5%BC%8F_07.html",
      "relativePath": "design-patterns/装饰器模式_07.md",
      "key": "v-5c3361db",
      "path": "/design-patterns/%E8%A3%85%E9%A5%B0%E5%99%A8%E6%A8%A1%E5%BC%8F_07.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、演示",
          "slug": "二、演示"
        },
        {
          "level": 2,
          "title": "三、场景",
          "slug": "三、场景"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        },
        {
          "level": 2,
          "title": "五、装饰器的原理",
          "slug": "五、装饰器的原理"
        },
        {
          "level": 2,
          "title": "六、装饰器库",
          "slug": "六、装饰器库"
        },
        {
          "level": 2,
          "title": "七、示例",
          "slug": "七、示例"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "观察者模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F_10.html",
      "relativePath": "design-patterns/观察者模式_10.md",
      "key": "v-273ce594",
      "path": "/design-patterns/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F_10.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、演示",
          "slug": "二、演示"
        },
        {
          "level": 2,
          "title": "三、场景",
          "slug": "三、场景"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        },
        {
          "level": 2,
          "title": "五、示例",
          "slug": "五、示例"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "设计原则",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99_03.html",
      "relativePath": "design-patterns/设计原则_03.md",
      "key": "v-42b0aa6b",
      "path": "/design-patterns/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99_03.html",
      "headers": [
        {
          "level": 2,
          "title": "一、 何为设计",
          "slug": "一、-何为设计"
        },
        {
          "level": 2,
          "title": "二、五大设计原则（SOLID）",
          "slug": "二、五大设计原则-solid"
        },
        {
          "level": 2,
          "title": "三、从设计到模式",
          "slug": "三、从设计到模式"
        },
        {
          "level": 2,
          "title": "四、介绍23种设计模式",
          "slug": "四、介绍23种设计模式"
        },
        {
          "level": 2,
          "title": "五、如何学习设计模式",
          "slug": "五、如何学习设计模式"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "用设计模式实现一个购物车",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E8%B4%AD%E7%89%A9%E8%BD%A6_14.html",
      "relativePath": "design-patterns/购物车_14.md",
      "key": "v-d837454e",
      "path": "/design-patterns/%E8%B4%AD%E7%89%A9%E8%BD%A6_14.html",
      "headers": [
        {
          "level": 2,
          "title": "UML类图分析各个模块",
          "slug": "uml类图分析各个模块"
        },
        {
          "level": 2,
          "title": "文件结构",
          "slug": "文件结构"
        },
        {
          "level": 2,
          "title": "用到的设计模式",
          "slug": "用到的设计模式"
        },
        {
          "level": 2,
          "title": "代码实现",
          "slug": "代码实现"
        },
        {
          "level": 3,
          "title": "api/list.json",
          "slug": "api-list-json"
        },
        {
          "level": 3,
          "title": "util/log.js",
          "slug": "util-log-js"
        },
        {
          "level": 3,
          "title": "config/config.js",
          "slug": "config-config-js"
        },
        {
          "level": 3,
          "title": "List/CreateItem.js",
          "slug": "list-createitem-js"
        },
        {
          "level": 3,
          "title": "List/Item.js",
          "slug": "list-item-js"
        },
        {
          "level": 3,
          "title": "List/List.js",
          "slug": "list-list-js"
        },
        {
          "level": 3,
          "title": "ShoppingCart/GetCart.js",
          "slug": "shoppingcart-getcart-js"
        },
        {
          "level": 3,
          "title": "ShoppingCart/ShoppingCart.js",
          "slug": "shoppingcart-shoppingcart-js"
        },
        {
          "level": 3,
          "title": "App.js",
          "slug": "app-js"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/interview-advanced/",
      "relativePath": "interview-advanced/README.md",
      "key": "v-394bcf50",
      "path": "/interview-advanced/",
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "迭代器模式",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F_11.html",
      "relativePath": "design-patterns/迭代器模式_11.md",
      "key": "v-742c0b9f",
      "path": "/design-patterns/%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F_11.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、演示",
          "slug": "二、演示"
        },
        {
          "level": 2,
          "title": "三、场景",
          "slug": "三、场景"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "Vue组件化和响应式",
      "frontmatter": {},
      "regularPath": "/interview-advanced/Vue%E7%BB%84%E4%BB%B6%E5%8C%96%E5%92%8C%E5%93%8D%E5%BA%94%E5%BC%8F.html",
      "relativePath": "interview-advanced/Vue组件化和响应式.md",
      "key": "v-48eab3f8",
      "path": "/interview-advanced/Vue%E7%BB%84%E4%BB%B6%E5%8C%96%E5%92%8C%E5%93%8D%E5%BA%94%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "组件化",
          "slug": "组件化"
        },
        {
          "level": 3,
          "title": "MVVM",
          "slug": "mvvm"
        },
        {
          "level": 2,
          "title": "响应式",
          "slug": "响应式"
        },
        {
          "level": 3,
          "title": "实现一个简单的视图更新",
          "slug": "实现一个简单的视图更新"
        }
      ],
      "lastUpdated": "9/3/2022, 4:41:04 PM"
    },
    {
      "title": "适配器",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F_06.html",
      "relativePath": "design-patterns/适配器模式_06.md",
      "key": "v-25a26300",
      "path": "/design-patterns/%E9%80%82%E9%85%8D%E5%99%A8%E6%A8%A1%E5%BC%8F_06.html",
      "headers": [
        {
          "level": 2,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 2,
          "title": "二、演示",
          "slug": "二、演示"
        },
        {
          "level": 2,
          "title": "三、场景",
          "slug": "三、场景"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "面向对象三要素",
      "frontmatter": {},
      "regularPath": "/design-patterns/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1_01.html",
      "relativePath": "design-patterns/面向对象_01.md",
      "key": "v-7241972d",
      "path": "/design-patterns/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1_01.html",
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "前端路由原理",
      "frontmatter": {},
      "regularPath": "/interview-advanced/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E5%8E%9F%E7%90%86.html",
      "relativePath": "interview-advanced/前端路由原理.md",
      "key": "v-45fedbc2",
      "path": "/interview-advanced/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E5%8E%9F%E7%90%86.html",
      "headers": [
        {
          "level": 2,
          "title": "hash",
          "slug": "hash"
        },
        {
          "level": 2,
          "title": "H5 history",
          "slug": "h5-history"
        }
      ]
    },
    {
      "title": "渲染流程",
      "frontmatter": {},
      "regularPath": "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html",
      "relativePath": "interview-advanced/渲染流程.md",
      "key": "v-0c6dedf6",
      "path": "/interview-advanced/%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html",
      "headers": [
        {
          "level": 3,
          "title": "初次渲染过程",
          "slug": "初次渲染过程"
        },
        {
          "level": 3,
          "title": "更新渲染过程",
          "slug": "更新渲染过程"
        },
        {
          "level": 3,
          "title": "异步渲染",
          "slug": "异步渲染"
        }
      ],
      "lastUpdated": "9/3/2022, 4:41:04 PM"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/interview-advanced/mind-mapping.html",
      "relativePath": "interview-advanced/mind-mapping.md",
      "key": "v-8dc10c0a",
      "path": "/interview-advanced/mind-mapping.html",
      "headers": [
        {
          "level": 3,
          "title": "知识体系思维导图",
          "slug": "知识体系思维导图"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/interview-basis/",
      "relativePath": "interview-basis/README.md",
      "key": "v-741947da",
      "path": "/interview-basis/",
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "模板编译",
      "frontmatter": {},
      "regularPath": "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html",
      "relativePath": "interview-advanced/模板编译.md",
      "key": "v-3df9de48",
      "path": "/interview-advanced/%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html",
      "headers": [
        {
          "level": 2,
          "title": "vue-template-compiler",
          "slug": "vue-template-compiler"
        },
        {
          "level": 3,
          "title": "通过模板渲染看 v-model",
          "slug": "通过模板渲染看-v-model"
        }
      ],
      "lastUpdated": "9/3/2022, 4:41:04 PM"
    },
    {
      "title": "Vue 使用和原理",
      "frontmatter": {},
      "regularPath": "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html",
      "relativePath": "interview-advanced/Vue使用.md",
      "key": "v-1a1aa737",
      "path": "/interview-advanced/Vue%E4%BD%BF%E7%94%A8.html",
      "lastUpdated": "5/26/2021, 5:56:39 PM"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/interview-basis/mind-mapping.html",
      "relativePath": "interview-basis/mind-mapping.md",
      "key": "v-d9e1fff2",
      "path": "/interview-basis/mind-mapping.html",
      "headers": [
        {
          "level": 2,
          "title": "知识体系思维导图",
          "slug": "知识体系思维导图"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "复杂设计库的设计",
      "frontmatter": {},
      "regularPath": "/koa2/database-design.html",
      "relativePath": "koa2/database-design.md",
      "key": "v-64d8620a",
      "path": "/koa2/database-design.html",
      "headers": [
        {
          "level": 2,
          "title": "嵌套数据模型",
          "slug": "嵌套数据模型"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "错误处理机制",
      "frontmatter": {},
      "regularPath": "/koa2/error-handling-mechanism.html",
      "relativePath": "koa2/error-handling-mechanism.md",
      "key": "v-080f25fb",
      "path": "/koa2/error-handling-mechanism.html",
      "headers": [
        {
          "level": 2,
          "title": "错误处理",
          "slug": "错误处理"
        },
        {
          "level": 2,
          "title": "自定义错误处理中间件",
          "slug": "自定义错误处理中间件"
        },
        {
          "level": 2,
          "title": "使用koa-json-error进行错误处理",
          "slug": "使用koa-json-error进行错误处理"
        },
        {
          "level": 2,
          "title": "使用koa-parameter校验参数",
          "slug": "使用koa-parameter校验参数"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Koa JWT认证",
      "frontmatter": {},
      "regularPath": "/koa2/jwt-koa.html",
      "relativePath": "koa2/jwt-koa.md",
      "key": "v-38c86b6d",
      "path": "/koa2/jwt-koa.html",
      "headers": [
        {
          "level": 2,
          "title": "Session",
          "slug": "session"
        },
        {
          "level": 2,
          "title": "JWT",
          "slug": "jwt"
        },
        {
          "level": 2,
          "title": "session vs JWT",
          "slug": "session-vs-jwt"
        },
        {
          "level": 2,
          "title": "Node中的JWT",
          "slug": "node中的jwt"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Koa 上传图片",
      "frontmatter": {},
      "regularPath": "/koa2/koa-upload.html",
      "relativePath": "koa2/koa-upload.md",
      "key": "v-e3b5594a",
      "path": "/koa2/koa-upload.html",
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Koa介绍",
      "frontmatter": {},
      "regularPath": "/koa2/koa1.html",
      "relativePath": "koa2/koa1.md",
      "key": "v-0586fa3b",
      "path": "/koa2/koa1.html",
      "headers": [
        {
          "level": 2,
          "title": "Koa的概念和使用",
          "slug": "koa的概念和使用"
        },
        {
          "level": 2,
          "title": "Koa中间件和洋葱模型",
          "slug": "koa中间件和洋葱模型"
        },
        {
          "level": 3,
          "title": "中间件",
          "slug": "中间件"
        },
        {
          "level": 3,
          "title": "洋葱模型",
          "slug": "洋葱模型"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Koa路由",
      "frontmatter": {},
      "regularPath": "/koa2/koa2.html",
      "relativePath": "koa2/koa2.md",
      "key": "v-563396ca",
      "path": "/koa2/koa2.html",
      "headers": [
        {
          "level": 2,
          "title": "Koa路由概念和使用",
          "slug": "koa路由概念和使用"
        },
        {
          "level": 2,
          "title": "多中间件功能",
          "slug": "多中间件功能"
        },
        {
          "level": 2,
          "title": "HTTP options方法",
          "slug": "http-options方法"
        },
        {
          "level": 2,
          "title": "allowedMethods的作用",
          "slug": "allowedmethods的作用"
        },
        {
          "level": 2,
          "title": "RESTful API最佳实践",
          "slug": "restful-api最佳实践"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "NoSQL和MongoDB",
      "frontmatter": {},
      "regularPath": "/koa2/nosql-mongodb.html",
      "relativePath": "koa2/nosql-mongodb.md",
      "key": "v-04f76312",
      "path": "/koa2/nosql-mongodb.html",
      "headers": [
        {
          "level": 2,
          "title": "NoSQL简介",
          "slug": "nosql简介"
        },
        {
          "level": 3,
          "title": "NoSQL数据库分类",
          "slug": "nosql数据库分类"
        },
        {
          "level": 3,
          "title": "NoSQL的好处",
          "slug": "nosql的好处"
        },
        {
          "level": 2,
          "title": "MongoDB",
          "slug": "mongodb"
        },
        {
          "level": 2,
          "title": "MongoDB Atlas",
          "slug": "mongodb-atlas"
        },
        {
          "level": 2,
          "title": "mongoose的使用",
          "slug": "mongoose的使用"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/koa2/restful.html",
      "relativePath": "koa2/restful.md",
      "key": "v-30f91689",
      "path": "/koa2/restful.html",
      "headers": [
        {
          "level": 2,
          "title": "REST是什么（Representational State Transfer）",
          "slug": "rest是什么-representational-state-transfer"
        },
        {
          "level": 2,
          "title": "REST的6个限制",
          "slug": "rest的6个限制"
        },
        {
          "level": 3,
          "title": "客户-服务器（Client-Server）CS架构限制",
          "slug": "客户-服务器-client-server-cs架构限制"
        },
        {
          "level": 3,
          "title": "无状态（Stateless）",
          "slug": "无状态-stateless"
        },
        {
          "level": 3,
          "title": "缓存（Cache）",
          "slug": "缓存-cache"
        },
        {
          "level": 3,
          "title": "统一接口（uniform Interface）",
          "slug": "统一接口-uniform-interface"
        },
        {
          "level": 3,
          "title": "分层系统（Layered System）",
          "slug": "分层系统-layered-system"
        },
        {
          "level": 3,
          "title": "按需代码（Code-On-Demand 可选）",
          "slug": "按需代码-code-on-demand-可选"
        },
        {
          "level": 2,
          "title": "统一接口的限制（认识REST的接口可以设计成什么样）",
          "slug": "统一接口的限制-认识rest的接口可以设计成什么样"
        },
        {
          "level": 2,
          "title": "什么是RESTful API",
          "slug": "什么是restful-api"
        },
        {
          "level": 2,
          "title": "RESTful API是什么样",
          "slug": "restful-api是什么样"
        },
        {
          "level": 2,
          "title": "RESTful API设计最佳实践",
          "slug": "restful-api设计最佳实践"
        },
        {
          "level": 3,
          "title": "请求设计规范",
          "slug": "请求设计规范"
        },
        {
          "level": 3,
          "title": "响应设计规范",
          "slug": "响应设计规范"
        },
        {
          "level": 3,
          "title": "安全",
          "slug": "安全"
        },
        {
          "level": 3,
          "title": "开发者友好",
          "slug": "开发者友好"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Koa控制器",
      "frontmatter": {},
      "regularPath": "/koa2/koa3.html",
      "relativePath": "koa2/koa3.md",
      "key": "v-b775220a",
      "path": "/koa2/koa3.html",
      "headers": [
        {
          "level": 2,
          "title": "控制器简介",
          "slug": "控制器简介"
        },
        {
          "level": 2,
          "title": "获取HTTP请求参数",
          "slug": "获取http请求参数"
        },
        {
          "level": 2,
          "title": "发送HTTP响应",
          "slug": "发送http响应"
        },
        {
          "level": 3,
          "title": "操作步骤",
          "slug": "操作步骤-2"
        },
        {
          "level": 3,
          "title": "编写控制器",
          "slug": "编写控制器"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Node.js在前后端的区别",
      "frontmatter": {},
      "regularPath": "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "relativePath": "node/Node.js在前后端的区别.md",
      "key": "v-1b815a80",
      "path": "/node/Node.js%E5%9C%A8%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "headers": [
        {
          "level": 2,
          "title": "Node.js 从工程化工具到后端服务应用的转变和区别",
          "slug": "node-js-从工程化工具到后端服务应用的转变和区别"
        },
        {
          "level": 3,
          "title": "运行环境",
          "slug": "运行环境"
        },
        {
          "level": 3,
          "title": "受众用户",
          "slug": "受众用户"
        },
        {
          "level": 3,
          "title": "问题调试",
          "slug": "问题调试"
        },
        {
          "level": 3,
          "title": "关注点",
          "slug": "关注点"
        }
      ],
      "lastUpdated": "6/8/2022, 4:31:13 PM"
    },
    {
      "title": "如何处理多进程",
      "frontmatter": {},
      "regularPath": "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html",
      "relativePath": "node/多进程问题如何处理.md",
      "key": "v-84156036",
      "path": "/node/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86.html",
      "headers": [
        {
          "level": 3,
          "title": "cluster 模式",
          "slug": "cluster-模式"
        },
        {
          "level": 3,
          "title": "PM2",
          "slug": "pm2"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Web 安全威胁解析",
      "frontmatter": {},
      "regularPath": "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html",
      "relativePath": "HTTP/Web安全威胁浅析.md",
      "key": "v-d58a29f4",
      "path": "/HTTP/Web%E5%AE%89%E5%85%A8%E5%A8%81%E8%83%81%E6%B5%85%E6%9E%90.html",
      "headers": [
        {
          "level": 2,
          "title": "Web 安全攻击概述",
          "slug": "web-安全攻击概述"
        },
        {
          "level": 2,
          "title": "验证机制安全",
          "slug": "验证机制安全"
        },
        {
          "level": 2,
          "title": "会话管理机制",
          "slug": "会话管理机制"
        },
        {
          "level": 2,
          "title": "SQL 注入攻击",
          "slug": "sql-注入攻击"
        },
        {
          "level": 2,
          "title": "XSS 攻击（跨站脚本攻击）",
          "slug": "xss-攻击-跨站脚本攻击"
        },
        {
          "level": 2,
          "title": "CSRF 攻击",
          "slug": "csrf-攻击"
        }
      ],
      "lastUpdated": "8/31/2021, 5:57:15 PM"
    },
    {
      "title": "侧边栏",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
      "relativePath": "cms-vue/侧边栏.md",
      "key": "v-b01acab0",
      "path": "/cms-vue/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "el-menu",
          "slug": "el-menu"
        },
        {
          "level": 2,
          "title": "el-submenu",
          "slug": "el-submenu"
        },
        {
          "level": 2,
          "title": "侧边栏 实现",
          "slug": "侧边栏-实现"
        },
        {
          "level": 3,
          "title": "实现 sidebar",
          "slug": "实现-sidebar"
        },
        {
          "level": 3,
          "title": "实现 sidebar-item",
          "slug": "实现-sidebar-item"
        },
        {
          "level": 3,
          "title": "实现 app-link",
          "slug": "实现-app-link"
        },
        {
          "level": 3,
          "title": "实现 item",
          "slug": "实现-item"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "HTTP 协议结构和通讯原理",
      "frontmatter": {},
      "regularPath": "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html",
      "relativePath": "HTTP/HTTP协议结构和通讯原理.md",
      "key": "v-5e30c7e3",
      "path": "/HTTP/HTTP%E5%8D%8F%E8%AE%AE%E7%BB%93%E6%9E%84%E5%92%8C%E9%80%9A%E8%AE%AF%E5%8E%9F%E7%90%86.html",
      "headers": [
        {
          "level": 2,
          "title": "协议特点",
          "slug": "协议特点"
        },
        {
          "level": 2,
          "title": "URI 和 URL",
          "slug": "uri-和-url"
        },
        {
          "level": 2,
          "title": "HTTP 报文结构分析",
          "slug": "http-报文结构分析"
        },
        {
          "level": 2,
          "title": "请求报文",
          "slug": "请求报文"
        },
        {
          "level": 2,
          "title": "响应报文",
          "slug": "响应报文"
        },
        {
          "level": 2,
          "title": "请求方法剖析",
          "slug": "请求方法剖析"
        },
        {
          "level": 3,
          "title": "GET",
          "slug": "get"
        },
        {
          "level": 3,
          "title": "POST",
          "slug": "post"
        },
        {
          "level": 3,
          "title": "PUT",
          "slug": "put"
        },
        {
          "level": 3,
          "title": "HEAD",
          "slug": "head"
        },
        {
          "level": 3,
          "title": "DELETE",
          "slug": "delete"
        },
        {
          "level": 3,
          "title": "OPTIONS",
          "slug": "options"
        },
        {
          "level": 3,
          "title": "TRACE",
          "slug": "trace"
        },
        {
          "level": 3,
          "title": "CONNECT",
          "slug": "connect"
        },
        {
          "level": 2,
          "title": "状态码",
          "slug": "状态码"
        },
        {
          "level": 3,
          "title": "状态码详解",
          "slug": "状态码详解"
        },
        {
          "level": 3,
          "title": "常用状态码",
          "slug": "常用状态码"
        },
        {
          "level": 2,
          "title": "HTTP 状态管理：Cookie 与 Session",
          "slug": "http-状态管理-cookie-与-session"
        },
        {
          "level": 3,
          "title": "Cookie",
          "slug": "cookie"
        },
        {
          "level": 3,
          "title": "Session",
          "slug": "session"
        },
        {
          "level": 3,
          "title": "Cookie 与 Session 的不同",
          "slug": "cookie-与-session-的不同"
        }
      ],
      "lastUpdated": "6/2/2021, 5:53:09 PM"
    },
    {
      "title": "电子书列表",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html",
      "relativePath": "cms-vue/电子书列表.md",
      "key": "v-6798fa9a",
      "path": "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E5%88%97%E8%A1%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "服务端",
          "slug": "服务端"
        },
        {
          "level": 2,
          "title": "客户端",
          "slug": "客户端"
        }
      ],
      "lastUpdated": "5/14/2021, 5:10:17 PM"
    },
    {
      "title": "登录页",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html",
      "relativePath": "cms-vue/登录页.md",
      "key": "v-eed00f1c",
      "path": "/cms-vue/%E7%99%BB%E5%BD%95%E9%A1%B5.html",
      "headers": [
        {
          "level": 2,
          "title": "登录流程分析",
          "slug": "登录流程分析"
        },
        {
          "level": 2,
          "title": "路由处理实例",
          "slug": "路由处理实例"
        },
        {
          "level": 3,
          "title": "创建组件",
          "slug": "创建组件"
        },
        {
          "level": 3,
          "title": "配置路由",
          "slug": "配置路由"
        },
        {
          "level": 2,
          "title": "登录后台实现",
          "slug": "登录后台实现"
        },
        {
          "level": 3,
          "title": "创建 /user/login API",
          "slug": "创建-user-login-api"
        },
        {
          "level": 3,
          "title": "响应结果封装",
          "slug": "响应结果封装"
        },
        {
          "level": 3,
          "title": "登录用户数据库查询",
          "slug": "登录用户数据库查询"
        },
        {
          "level": 3,
          "title": "密码加密",
          "slug": "密码加密"
        },
        {
          "level": 3,
          "title": "参数校验",
          "slug": "参数校验"
        },
        {
          "level": 3,
          "title": "Token",
          "slug": "token"
        },
        {
          "level": 3,
          "title": "前端登录请求改造",
          "slug": "前端登录请求改造"
        },
        {
          "level": 3,
          "title": "JWT 认证",
          "slug": "jwt-认证"
        },
        {
          "level": 3,
          "title": "创建用户信息接口",
          "slug": "创建用户信息接口"
        }
      ],
      "lastUpdated": "4/30/2021, 11:25:38 AM"
    },
    {
      "title": "虚拟DOM和diff算法",
      "frontmatter": {},
      "regularPath": "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html",
      "relativePath": "interview-advanced/虚拟DOM和diff算法.md",
      "key": "v-524dacba",
      "path": "/interview-advanced/%E8%99%9A%E6%8B%9FDOM%E5%92%8Cdiff%E7%AE%97%E6%B3%95.html",
      "headers": [
        {
          "level": 2,
          "title": "用JS模拟DOM结构",
          "slug": "用js模拟dom结构"
        },
        {
          "level": 2,
          "title": "VDom核心",
          "slug": "vdom核心"
        },
        {
          "level": 3,
          "title": "snabbdom",
          "slug": "snabbdom"
        },
        {
          "level": 3,
          "title": "h",
          "slug": "h"
        },
        {
          "level": 3,
          "title": "vnode",
          "slug": "vnode"
        },
        {
          "level": 3,
          "title": "patch",
          "slug": "patch"
        },
        {
          "level": 2,
          "title": "diff 算法",
          "slug": "diff-算法"
        },
        {
          "level": 3,
          "title": "patchVnode",
          "slug": "patchvnode"
        },
        {
          "level": 3,
          "title": "updateChildren",
          "slug": "updatechildren"
        }
      ],
      "lastUpdated": "9/3/2022, 4:41:04 PM"
    },
    {
      "title": "RESTFull 最佳实践",
      "frontmatter": {},
      "regularPath": "/koa2/restful-practice.html",
      "relativePath": "koa2/restful-practice.md",
      "key": "v-29ab97db",
      "path": "/koa2/restful-practice.html",
      "headers": [
        {
          "level": 2,
          "title": "嵌套路由",
          "slug": "嵌套路由"
        },
        {
          "level": 2,
          "title": "互斥接口",
          "slug": "互斥接口"
        },
        {
          "level": 2,
          "title": "RESTful API最佳实践",
          "slug": "restful-api最佳实践"
        },
        {
          "level": 2,
          "title": "分页设计、模糊搜索、多字段模糊搜索实践",
          "slug": "分页设计、模糊搜索、多字段模糊搜索实践"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "数据模型的应用",
      "frontmatter": {},
      "regularPath": "/koa2/schema.html",
      "relativePath": "koa2/schema.md",
      "key": "v-aa6bf04a",
      "path": "/koa2/schema.html",
      "headers": [
        {
          "level": 2,
          "title": "个人信息schema设计",
          "slug": "个人信息schema设计"
        },
        {
          "level": 2,
          "title": "关注和粉丝模块的多对多关系设计",
          "slug": "关注和粉丝模块的多对多关系设计"
        },
        {
          "level": 2,
          "title": "话题Schema设计",
          "slug": "话题schema设计"
        },
        {
          "level": 2,
          "title": "用户属性用话题属性替代",
          "slug": "用户属性用话题属性替代"
        }
      ],
      "lastUpdated": "8/8/2022, 2:43:56 PM"
    },
    {
      "title": "Node.js高性能如何做到的",
      "frontmatter": {},
      "regularPath": "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html",
      "relativePath": "node/Node.js高性能如何做到的.md",
      "key": "v-1193cdf4",
      "path": "/node/Node.js%E9%AB%98%E6%80%A7%E8%83%BD%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E7%9A%84.html",
      "headers": [
        {
          "level": 2,
          "title": "Node.js 事件循环核心流程",
          "slug": "node-js-事件循环核心流程"
        },
        {
          "level": 3,
          "title": "运行起点",
          "slug": "运行起点"
        },
        {
          "level": 3,
          "title": "Node.js 事件循环",
          "slug": "node-js-事件循环"
        },
        {
          "level": 2,
          "title": "Node.js 的事件驱动",
          "slug": "node-js-的事件驱动"
        },
        {
          "level": 3,
          "title": "响应分析",
          "slug": "响应分析"
        },
        {
          "level": 3,
          "title": "单线程/多线程",
          "slug": "单线程-多线程"
        },
        {
          "level": 3,
          "title": "应用场景",
          "slug": "应用场景"
        }
      ],
      "lastUpdated": "6/8/2022, 4:31:13 PM"
    },
    {
      "title": "如何快速构建 RESTful 服务",
      "frontmatter": {},
      "regularPath": "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html",
      "relativePath": "node/如何快速构建 RESTful 服务.md",
      "key": "v-1521d2d0",
      "path": "/node/%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%20RESTful%20%E6%9C%8D%E5%8A%A1.html",
      "headers": [
        {
          "level": 3,
          "title": "MVC 与 MSVC",
          "slug": "mvc-与-msvc"
        },
        {
          "level": 3,
          "title": "案例实践",
          "slug": "案例实践"
        }
      ],
      "lastUpdated": "6/21/2022, 3:47:25 PM"
    },
    {
      "title": "基于 HTTP 的功能追加协议",
      "frontmatter": {},
      "regularPath": "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html",
      "relativePath": "HTTP/基于HTTP追加协议.md",
      "key": "v-7ffcecb0",
      "path": "/HTTP/%E5%9F%BA%E4%BA%8EHTTP%E8%BF%BD%E5%8A%A0%E5%8D%8F%E8%AE%AE.html",
      "headers": [
        {
          "level": 2,
          "title": "HTTP 协议的瓶颈",
          "slug": "http-协议的瓶颈"
        },
        {
          "level": 2,
          "title": "WebSocket 与 HTTP",
          "slug": "websocket-与-http"
        },
        {
          "level": 3,
          "title": "WebSocket 协议",
          "slug": "websocket-协议"
        },
        {
          "level": 3,
          "title": "如何实现实时信息传递",
          "slug": "如何实现实时信息传递"
        },
        {
          "level": 2,
          "title": "SPDY",
          "slug": "spdy"
        },
        {
          "level": 3,
          "title": "SPDY 的意义",
          "slug": "spdy-的意义"
        },
        {
          "level": 2,
          "title": "HTTP2.0",
          "slug": "http2-0"
        },
        {
          "level": 3,
          "title": "HTTP2.0 性能增强的核心：二进制分帧",
          "slug": "http2-0-性能增强的核心-二进制分帧"
        },
        {
          "level": 2,
          "title": "HTTP3.0",
          "slug": "http3-0"
        },
        {
          "level": 3,
          "title": "HTTP2.0 历史遗留问题",
          "slug": "http2-0-历史遗留问题"
        },
        {
          "level": 3,
          "title": "QUIC 特性",
          "slug": "quic-特性"
        }
      ],
      "lastUpdated": "8/25/2021, 6:03:45 PM"
    },
    {
      "title": "电子书新增",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html",
      "relativePath": "cms-vue/电子书新增.md",
      "key": "v-95419a9a",
      "path": "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E6%96%B0%E5%A2%9E.html",
      "headers": [
        {
          "level": 2,
          "title": "服务端",
          "slug": "服务端"
        },
        {
          "level": 2,
          "title": "客户端",
          "slug": "客户端"
        }
      ],
      "lastUpdated": "4/30/2021, 11:25:38 AM"
    },
    {
      "title": "电子书上传",
      "frontmatter": {},
      "regularPath": "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html",
      "relativePath": "cms-vue/电子书上传.md",
      "key": "v-3a223289",
      "path": "/cms-vue/%E7%94%B5%E5%AD%90%E4%B9%A6%E4%B8%8A%E4%BC%A0.html",
      "headers": [
        {
          "level": 2,
          "title": "上传 API",
          "slug": "上传-api"
        },
        {
          "level": 2,
          "title": "电子书解析",
          "slug": "电子书解析"
        },
        {
          "level": 3,
          "title": "创建 book 表结构",
          "slug": "创建-book-表结构"
        },
        {
          "level": 3,
          "title": "从文件创建 Book 对象",
          "slug": "从文件创建-book-对象"
        },
        {
          "level": 3,
          "title": "数据创建 Book 对象",
          "slug": "数据创建-book-对象"
        },
        {
          "level": 3,
          "title": "epub解析应用",
          "slug": "epub解析应用"
        },
        {
          "level": 3,
          "title": "电子书解压",
          "slug": "电子书解压"
        },
        {
          "level": 3,
          "title": "电子书目录解析",
          "slug": "电子书目录解析"
        }
      ],
      "lastUpdated": "4/27/2021, 7:07:44 PM"
    },
    {
      "title": "HTTP 的特性和使用",
      "frontmatter": {},
      "regularPath": "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html",
      "relativePath": "HTTP/HTTP的特性和使用.md",
      "key": "v-060bca28",
      "path": "/HTTP/HTTP%E7%9A%84%E7%89%B9%E6%80%A7%E5%92%8C%E4%BD%BF%E7%94%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "HTTP 协议编码解码",
          "slug": "http-协议编码解码"
        },
        {
          "level": 3,
          "title": "编码规范",
          "slug": "编码规范"
        },
        {
          "level": 3,
          "title": "常见的编码规范介绍",
          "slug": "常见的编码规范介绍"
        },
        {
          "level": 3,
          "title": "问题",
          "slug": "问题"
        },
        {
          "level": 2,
          "title": "HTTP 协议-身份认证",
          "slug": "http-协议-身份认证"
        },
        {
          "level": 3,
          "title": "BASIC 认证",
          "slug": "basic-认证"
        },
        {
          "level": 3,
          "title": "DIGEST 认证",
          "slug": "digest-认证"
        },
        {
          "level": 3,
          "title": "SSL 客户端认证",
          "slug": "ssl-客户端认证"
        },
        {
          "level": 3,
          "title": "FormBase 认证",
          "slug": "formbase-认证"
        },
        {
          "level": 2,
          "title": "HTTP 协议-长连接与短连接",
          "slug": "http-协议-长连接与短连接"
        },
        {
          "level": 2,
          "title": "HTTP 中介-代理",
          "slug": "http-中介-代理"
        },
        {
          "level": 3,
          "title": "代理的作用",
          "slug": "代理的作用"
        },
        {
          "level": 2,
          "title": "HTTP 中介-网管",
          "slug": "http-中介-网管"
        },
        {
          "level": 2,
          "title": "HTTP 缓存",
          "slug": "http-缓存"
        },
        {
          "level": 3,
          "title": "HTTP 缓存工作方式",
          "slug": "http-缓存工作方式"
        },
        {
          "level": 3,
          "title": "缓存改进方案",
          "slug": "缓存改进方案"
        },
        {
          "level": 3,
          "title": "CDN 缓存工作方式",
          "slug": "cdn-缓存工作方式"
        },
        {
          "level": 3,
          "title": "浏览器操作对 HTTP 缓存的影响",
          "slug": "浏览器操作对-http-缓存的影响"
        },
        {
          "level": 2,
          "title": "HTTP 内容协商机制",
          "slug": "http-内容协商机制"
        },
        {
          "level": 3,
          "title": "内容协商方式",
          "slug": "内容协商方式"
        },
        {
          "level": 3,
          "title": "服务器驱动内容协商-请求首部集",
          "slug": "服务器驱动内容协商-请求首部集"
        },
        {
          "level": 3,
          "title": "近似匹配",
          "slug": "近似匹配"
        },
        {
          "level": 2,
          "title": "HTTP 断点续传和多线程下载",
          "slug": "http-断点续传和多线程下载"
        },
        {
          "level": 3,
          "title": "断点续传过程",
          "slug": "断点续传过程"
        }
      ],
      "lastUpdated": "7/1/2021, 5:59:14 PM"
    },
    {
      "title": "Vue进阶",
      "frontmatter": {},
      "regularPath": "/cms-vue/advance.html",
      "relativePath": "cms-vue/advance.md",
      "key": "v-4271bf9b",
      "path": "/cms-vue/advance.html",
      "headers": [
        {
          "level": 2,
          "title": "$on 和 $emit",
          "slug": "on-和-emit"
        },
        {
          "level": 2,
          "title": "directive 用法",
          "slug": "directive-用法"
        },
        {
          "level": 2,
          "title": "component 用法",
          "slug": "component-用法"
        },
        {
          "level": 2,
          "title": "extnd 用法",
          "slug": "extnd-用法"
        },
        {
          "level": 2,
          "title": "extend 进阶用法",
          "slug": "extend-进阶用法"
        },
        {
          "level": 2,
          "title": "use 用法",
          "slug": "use-用法"
        },
        {
          "level": 2,
          "title": "observable 用法",
          "slug": "observable-用法"
        },
        {
          "level": 2,
          "title": "slot 用法",
          "slug": "slot-用法"
        },
        {
          "level": 2,
          "title": "自定义 v-model",
          "slug": "自定义-v-model"
        },
        {
          "level": 2,
          "title": "nextTick 用法",
          "slug": "nexttick-用法"
        }
      ],
      "lastUpdated": "6/8/2022, 4:31:13 PM"
    }
  ],
  "themeConfig": {
    "activeHeaderLinks": false,
    "smoothScroll": true,
    "lastUpdated": "最后更新时间",
    "nav": [
      {
        "text": "笔记",
        "items": [
          {
            "text": "koa2",
            "link": "/koa2/restful"
          },
          {
            "text": "设计模式",
            "link": "/design-patterns/面向对象_01"
          },
          {
            "text": "面试基础",
            "link": "/interview-basis/mind-mapping"
          },
          {
            "text": "面试进阶",
            "link": "/interview-advanced/mind-mapping"
          },
          {
            "text": "vue koa 实现后台管理",
            "link": "/cms-vue/advance"
          },
          {
            "text": "HTTP协议",
            "link": "/HTTP/了解HTTP协议"
          },
          {
            "text": "node应用开发",
            "link": "/node/Node.js在前后端的区别"
          }
        ]
      }
    ],
    "sidebar": {
      "/koa2/": [
        {
          "title": "koa2",
          "collapsable": false,
          "children": [
            {
              "title": "认识RESTful",
              "path": "restful"
            },
            {
              "title": "认识Koa",
              "path": "koa1"
            },
            {
              "title": "Koa路由和RESTful实践",
              "path": "koa2"
            },
            {
              "title": "Koa控制器",
              "path": "koa3"
            },
            {
              "title": "多方案错误处理机制",
              "path": "error-handling-mechanism"
            },
            {
              "title": "NoSQL和MongoDB",
              "path": "nosql-mongodb"
            },
            {
              "title": "JWT在Koa的应用",
              "path": "jwt-koa"
            },
            {
              "title": "Koa图片上传",
              "path": "koa-upload"
            },
            {
              "title": "数据模型的应用",
              "path": "schema"
            },
            {
              "title": "RESTful最佳实践",
              "path": "restful-practice"
            },
            {
              "title": "数据库设计",
              "path": "database-design"
            }
          ]
        }
      ],
      "/design-patterns/": [
        {
          "title": "设计模式",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "面向对象",
              "path": "面向对象_01"
            },
            {
              "title": "UML 类图",
              "path": "UML 类图_02"
            },
            {
              "title": "设计原则",
              "path": "设计原则_03"
            },
            {
              "title": "工厂模式",
              "path": "工厂模式_04"
            },
            {
              "title": "单例模式",
              "path": "单例模式_05"
            },
            {
              "title": "适配器模式",
              "path": "适配器模式_06"
            },
            {
              "title": "装饰器模式",
              "path": "装饰器模式_07"
            },
            {
              "title": "代理模式",
              "path": "代理模式_08"
            },
            {
              "title": "外观模式",
              "path": "外观模式_9"
            },
            {
              "title": "观察者模式",
              "path": "观察者模式_10"
            },
            {
              "title": "迭代器模式",
              "path": "迭代器模式_11"
            },
            {
              "title": "状态模式",
              "path": "状态模式_12"
            },
            {
              "title": "其他设计模式",
              "path": "其他设计模式_13"
            },
            {
              "title": "实现一个购物车",
              "path": "购物车_14"
            }
          ]
        }
      ],
      "/interview-basis/": [
        {
          "title": "面试基础",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "CSS面试",
              "path": "mind-mapping"
            }
          ]
        }
      ],
      "/interview-advanced/": [
        {
          "title": "面试进阶",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "思维导图",
              "path": "mind-mapping"
            },
            {
              "title": "Vue使用",
              "path": "Vue使用"
            },
            {
              "title": "Vue组件化和响应式",
              "path": "Vue组件化和响应式"
            },
            {
              "title": "虚拟DOM和diff算法",
              "path": "虚拟DOM和diff算法"
            },
            {
              "title": "模板编译",
              "path": "模板编译"
            },
            {
              "title": "渲染流程",
              "path": "渲染流程"
            },
            {
              "title": "前端路由原理",
              "path": "前端路由原理"
            }
          ]
        }
      ],
      "/cms-vue/": [
        {
          "title": "vue koa 实现后台管理",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "Vue进阶",
              "path": "advance"
            },
            {
              "title": "Vuex 和 Vue-router 进阶",
              "path": "vuex-vue-router"
            },
            {
              "title": "前端框架搭建",
              "path": "前端框架搭建"
            },
            {
              "title": "后端框架搭建",
              "path": "后端框架搭建"
            },
            {
              "title": "功能分析",
              "path": "功能分析"
            },
            {
              "title": "用户登录",
              "path": "登录页"
            },
            {
              "title": "路由和权限校验",
              "path": "路由和权限校验"
            },
            {
              "title": "侧边栏",
              "path": "侧边栏"
            },
            {
              "title": "重定向",
              "path": "重定向"
            },
            {
              "title": "面包屑导航",
              "path": "面包屑导航"
            },
            {
              "title": "电子书上传",
              "path": "电子书上传"
            },
            {
              "title": "电子书新增",
              "path": "电子书新增"
            },
            {
              "title": "电子书编辑",
              "path": "电子书编辑"
            },
            {
              "title": "电子书列表",
              "path": "电子书列表"
            },
            {
              "title": "项目部署",
              "path": "项目部署"
            },
            {
              "title": "常用命令",
              "path": "常用命令"
            }
          ]
        }
      ],
      "/HTTP/": [
        {
          "title": "HTTP协议",
          "collapsable": false,
          "sidebarDepth": 4,
          "children": [
            {
              "title": "了解HTTP协议",
              "path": "了解HTTP协议"
            },
            {
              "title": "HTTP协议结构和通讯原理",
              "path": "HTTP协议结构和通讯原理"
            },
            {
              "title": "HTTP的特性和使用",
              "path": "HTTP的特性和使用"
            },
            {
              "title": "安全的HTTPS",
              "path": "安全的HTTPS"
            },
            {
              "title": "基于HTTP追加协议",
              "path": "基于HTTP追加协议"
            },
            {
              "title": "Web安全威胁浅析",
              "path": "Web安全威胁浅析"
            }
          ]
        }
      ],
      "/node/": [
        {
          "title": "node应用开发",
          "collapsable": false,
          "sidebarDepth": 4,
          "children": [
            {
              "title": "Node.js在前后端的区别",
              "path": "Node.js在前后端的区别"
            },
            {
              "title": "Node.js高性能如何做到的？",
              "path": "Node.js高性能如何做到的"
            },
            {
              "title": "如何快速构建 RESTful 服务",
              "path": "如何快速构建 RESTful 服务"
            },
            {
              "title": "多进程问题如何处理",
              "path": "多进程问题如何处理"
            }
          ]
        }
      ]
    }
  }
}